import type { Metadata } from "next";
import { plusJakartaSans } from "./fonts";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${plusJakartaSans.className} min-h-screen bg-[#0A4833]`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
